services:
  app:
    build: .
    container_name: trip-diary-be
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    networks:
      - backend
    entrypoint:
      [
        '/bin/sh',
        '-c',
        'chmod +x ./docker-entrypoint.sh && ./docker-entrypoint.sh',
      ]

  db:
    image: postgres:15-alpine
    container_name: trip-diary-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tripdiary
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: trip-diary-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
